# Generated by Django 3.1.2 on 2021-04-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_number', models.CharField(max_length=45)),
                ('copy_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year_of_publication', models.IntegerField()),
                ('current_status', models.CharField(choices=[('on-loan', 'on-loan'), ('on-shelf', 'on-shelf'), ('on-hold', 'on-hold'), ('on-loan-and-on-hold', 'on-loan-and-on-hold')], max_length=255)),
                ('Img1', models.ImageField(default='images/no-image.jpg', upload_to='images/')),
                ('shelf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.shelf')),
            ],
            options={
                'unique_together': {('isbn_number', 'copy_number')},
            },
        ),
    ]
