# Generated by Django 3.1.2 on 2021-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Science', 'Science'), ('Business', 'Business'), ('Biography', 'Biography'), ('Literature', 'Literature'), ('Others', 'Others')], default='Others', max_length=255),
        ),
    ]
