# Generated by Django 3.1.2 on 2021-04-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210419_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='hold_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hold',
            name='hold_limit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
