# Generated by Django 3.1.2 on 2021-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210419_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='hold_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hold',
            name='hold_limit',
            field=models.DateTimeField(null=True),
        ),
    ]
