# Generated by Django 3.1.2 on 2021-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20201019_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='books_withdrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_faculty',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unpaid_fines',
            field=models.IntegerField(default=0),
        ),
    ]
