# Generated by Django 3.1.2 on 2021-04-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20210418_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('id2', models.IntegerField()),
            ],
        ),
    ]
